2015/12/05 22:38:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  la autentificación password falló para el usuario «root»' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\rrhh\protected\views\layouts\main.php(35): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\rrhh\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#16 C:\xampp\htdocs\rrhh\protected\controllers\SiteController.php(34): CController->render('index')
#17 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#22 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#23 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\rrhh\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/rrhh/
---
2015/12/05 22:49:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\rrhh\protected\views\layouts\main.php(35): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\rrhh\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#16 C:\xampp\htdocs\rrhh\protected\controllers\SiteController.php(34): CController->render('index')
#17 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#22 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#23 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\rrhh\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/rrhh/
---
2015/12/05 22:58:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\rrhh\protected\views\layouts\main.php(35): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\rrhh\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#16 C:\xampp\htdocs\rrhh\protected\controllers\SiteController.php(34): CController->render('index')
#17 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#22 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#23 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\rrhh\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/rrhh/
---
2015/12/05 23:01:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\rrhh\protected\views\layouts\main.php(35): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\rrhh\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#16 C:\xampp\htdocs\rrhh\protected\controllers\SiteController.php(34): CController->render('index')
#17 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#22 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#23 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\rrhh\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/rrhh/
---
2015/12/05 23:08:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  no existe el rol «root»' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\rrhh\protected\views\layouts\main.php(35): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\rrhh\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#16 C:\xampp\htdocs\rrhh\protected\controllers\SiteController.php(34): CController->render('index')
#17 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#22 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#23 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\rrhh\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/rrhh/
---
2015/12/05 23:09:51 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42P01]: Undefined table: 7 ERROR:  no existe la relación «id»
LINE 1: Select * from id
                      ^. The SQL statement executed was: Select * from id.
in C:\xampp\htdocs\rrhh\protected\views\layouts\main.php (35)
in C:\xampp\htdocs\rrhh\protected\views\layouts\column1.php (6)
in C:\xampp\htdocs\rrhh\protected\controllers\SiteController.php (34)
2015/12/05 23:09:51 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42P01]: Undefined table: 7 ERROR:  no existe la relación «id»
LINE 1: Select * from id
                      ^. The SQL statement executed was: Select * from id' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\rrhh\protected\views\layouts\main.php(35): CDbCommand->queryAll()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\rrhh\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\rrhh\protected\controllers\SiteController.php(34): CController->render('index')
#14 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#21 C:\xampp\htdocs\rrhh\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/rrhh/
---
2015/12/06 15:22:34 [error] [exception.CException] exception 'CException' with message 'CWebUser y sus behaviors no tienen un método o closure llamado "isGuest".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\rrhh\protected\views\layouts\main.php(29): CComponent->__call('isGuest', Array)
#1 C:\xampp\htdocs\rrhh\protected\views\layouts\main.php(29): CWebUser->isGuest()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\rrhh\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\rrhh\protected\controllers\SiteController.php(34): CController->render('index')
#14 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#21 C:\xampp\htdocs\rrhh\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/rrhh/index.php
---
2015/12/08 14:54:51 [error] [exception.CException] exception 'CException' with message 'SitioController no ha podido encontrar la vista "index" solicitada.' in D:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 D:\xampp\htdocs\rrhh\protected\controllers\SitioController.php(19): CController->render('index')
#2 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SitioController->actionIndex()
#3 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 D:\xampp\htdocs\rrhh\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/rrhh/
---
2015/12/08 15:03:37 [error] [system.db.CDbCommand] Error in preparing SQL: DELETE FROM 'YiiSession' WHERE expire<:expire
in D:\xampp\htdocs\rrhh\protected\views\layouts\main.php (29)
in D:\xampp\htdocs\rrhh\protected\views\layouts\column1.php (6)
in D:\xampp\htdocs\rrhh\protected\controllers\SitioController.php (19)
2015/12/08 15:03:37 [error] [system.db.CDbCommand] CDbCommand::execute() falló: CDbCommand falló al preparar la sentencia SQL: SQLSTATE[HY000]: General error: 1 no such table: YiiSession. La sentencia SQL ejecutada fue: DELETE FROM 'YiiSession' WHERE expire<:expire.
in D:\xampp\htdocs\rrhh\protected\views\layouts\main.php (29)
in D:\xampp\htdocs\rrhh\protected\views\layouts\column1.php (6)
in D:\xampp\htdocs\rrhh\protected\controllers\SitioController.php (19)
2015/12/08 15:12:35 [error] [exception.CException] exception 'CException' with message 'La propiedad "AccesoHojaDeVida"."password" no se encuentra definida.' in D:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 D:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(2728): CActiveRecord->__get('password')
#2 D:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(2451): CHtml::resolveValue(Object(AccesoHojaDeVida), 'password')
#3 D:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1807): CHtml::activeInputField('password', Object(AccesoHojaDeVida), 'password', Array)
#4 D:\xampp\htdocs\yii\framework\web\widgets\CActiveForm.php(838): CHtml::activePasswordField(Object(AccesoHojaDeVida), 'password', Array)
#5 D:\xampp\htdocs\rrhh\protected\views\sitio\index.php(45): CActiveForm->passwordField(Object(AccesoHojaDeVida), 'password', Array)
#6 D:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('D:\\xampp\\htdocs...')
#7 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\\xampp\\htdocs...', Array, true)
#8 D:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('D:\\xampp\\htdocs...', Array, true)
#9 D:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 D:\xampp\htdocs\rrhh\protected\controllers\SitioController.php(20): CController->render('index', Array)
#11 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SitioController->actionIndex()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#17 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#18 D:\xampp\htdocs\rrhh\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/rrhh/
---
2015/12/08 09:58:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 10:55:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 10:55:35 [error] [exception.PDOException] exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: :passw' in D:\xampp\htdocs\yii\framework\db\CDbCommand.php:275
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbCommand.php(275): PDOStatement->bindValue(':passw', 'dsdsd', 2)
#1 D:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php(568): CDbCommand->bindValue(':passw', 'dsdsd')
#2 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1372): CDbCommandBuilder->bindValues(Object(CDbCommand), Array)
#3 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(807): CJoinQuery->createCommand(Object(CPgsqlCommandBuilder))
#4 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(440): CJoinElement->runQuery(Object(CJoinQuery))
#5 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#6 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1361): CActiveFinder->query(Object(CDbCriteria), false)
#7 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1461): CActiveRecord->query(Object(CDbCriteria))
#8 D:\xampp\htdocs\rrhh\protected\controllers\SitioController.php(28): CActiveRecord->find(Array)
#9 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SitioController->actionIndex()
#10 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#15 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#17 {main}
REQUEST_URI=/rrhh/
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 10:56:21 [error] [exception.PDOException] exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: :passw' in D:\xampp\htdocs\yii\framework\db\CDbCommand.php:275
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbCommand.php(275): PDOStatement->bindValue(':passw', 'dsdsd', 2)
#1 D:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php(568): CDbCommand->bindValue(':passw', 'dsdsd')
#2 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1372): CDbCommandBuilder->bindValues(Object(CDbCommand), Array)
#3 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(807): CJoinQuery->createCommand(Object(CPgsqlCommandBuilder))
#4 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(440): CJoinElement->runQuery(Object(CJoinQuery))
#5 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#6 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1361): CActiveFinder->query(Object(CDbCriteria), false)
#7 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1461): CActiveRecord->query(Object(CDbCriteria))
#8 D:\xampp\htdocs\rrhh\protected\controllers\SitioController.php(28): CActiveRecord->find(Array)
#9 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SitioController->actionIndex()
#10 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#15 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#17 {main}
REQUEST_URI=/rrhh/
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 10:56:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 10:56:28 [error] [exception.PDOException] exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: :passw' in D:\xampp\htdocs\yii\framework\db\CDbCommand.php:275
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbCommand.php(275): PDOStatement->bindValue(':passw', 'fdsfds', 2)
#1 D:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php(568): CDbCommand->bindValue(':passw', 'fdsfds')
#2 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1372): CDbCommandBuilder->bindValues(Object(CDbCommand), Array)
#3 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(807): CJoinQuery->createCommand(Object(CPgsqlCommandBuilder))
#4 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(440): CJoinElement->runQuery(Object(CJoinQuery))
#5 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#6 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1361): CActiveFinder->query(Object(CDbCriteria), false)
#7 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1461): CActiveRecord->query(Object(CDbCriteria))
#8 D:\xampp\htdocs\rrhh\protected\controllers\SitioController.php(28): CActiveRecord->find(Array)
#9 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SitioController->actionIndex()
#10 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#15 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#17 {main}
REQUEST_URI=/rrhh/
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 10:56:48 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42703]: Undefined column: 7 ERROR:  no existe la columna «fdsfds»
LINE 1: ...id") WHERE (correo_electronico =$1 AND passwd=md5("fdsfds"))
                                                             ^. La sentencia SQL ejecutada fue: SELECT "t"."acceso_id" AS "t0_c0", "t"."correo_electronico" AS "t0_c1", "t"."passwd" AS "t0_c2", "t"."sw_estado" AS "t0_c3", "t"."fecha_registro" AS "t0_c4", "t"."passwd_default" AS "t0_c5", "objHojaDeVida"."hv_id" AS "t1_c0", "objHojaDeVida"."empresa_id" AS "t1_c1", "objHojaDeVida"."lugar_expedicion" AS "t1_c2", "objHojaDeVida"."fecha_inscripcion" AS "t1_c3", "objHojaDeVida"."acceso_id" AS "t1_c4", "objHojaDeVida"."estado_id" AS "t1_c5", "objHojaDeVida"."tipo_documento_id" AS "t1_c6", "objHojaDeVida"."documento_id" AS "t1_c7", "objHojaDeVida"."fecha_actualizacion" AS "t1_c8", "objHojaDeVida"."user_id_valido" AS "t1_c9", "objHojaDeVida"."fecha_validacion" AS "t1_c10", "objHojaDeVida"."user_id_clasifico" AS "t1_c11", "objHojaDeVida"."fecha_clasificacion" AS "t1_c12", "objHojaDeVida"."fecha_expedicion_documento" AS "t1_c13", "objHojaDeVida"."user_id_inactivo" AS "t1_c14", "objHojaDeVida"."fecha_inactivacion" AS "t1_c15" FROM "acceso_hoja_de_vida" "t"  LEFT OUTER JOIN "hoja_de_vida" "objHojaDeVida" ON ("t"."acceso_id"="objHojaDeVida"."hv_id") WHERE (correo_electronico =:correo AND passwd=md5("fdsfds")).
in D:\xampp\htdocs\rrhh\protected\controllers\SitioController.php (27)
in D:\xampp\htdocs\rrhh\index.php (14)
2015/12/08 10:56:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[42703]: Undefined column: 7 ERROR:  no existe la columna «fdsfds»
LINE 1: ...id") WHERE (correo_electronico =$1 AND passwd=md5("fdsfds"))
                                                             ^. The SQL statement executed was: SELECT "t"."acceso_id" AS "t0_c0", "t"."correo_electronico" AS "t0_c1", "t"."passwd" AS "t0_c2", "t"."sw_estado" AS "t0_c3", "t"."fecha_registro" AS "t0_c4", "t"."passwd_default" AS "t0_c5", "objHojaDeVida"."hv_id" AS "t1_c0", "objHojaDeVida"."empresa_id" AS "t1_c1", "objHojaDeVida"."lugar_expedicion" AS "t1_c2", "objHojaDeVida"."fecha_inscripcion" AS "t1_c3", "objHojaDeVida"."acceso_id" AS "t1_c4", "objHojaDeVida"."estado_id" AS "t1_c5", "objHojaDeVida"."tipo_documento_id" AS "t1_c6", "objHojaDeVida"."documento_id" AS "t1_c7", "objHojaDeVida"."fecha_actualizacion" AS "t1_c8", "objHojaDeVida"."user_id_valido" AS "t1_c9", "objHojaDeVida"."fecha_validacion" AS "t1_c10", "objHojaDeVida"."user_id_clasifico" AS "t1_c11", "objHojaDeVida"."fecha_clasificacion" AS "t1_c12", "objHojaDeVida"."fecha_expedicion_documento" AS "t1_c13", "objHojaDeVida"."user_id_inactivo" AS "t1_c14", "objHojaDeVida"."fecha_inactivacion" AS "t1_c15" FROM "acceso_hoja_de_vida" "t"  LEFT OUTER JOIN "hoja_de_vida" "objHojaDeVida" ON ("t"."acceso_id"="objHojaDeVida"."hv_id") WHERE (correo_electronico =:correo AND passwd=md5("fdsfds"))' in D:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(808): CDbCommand->queryAll()
#2 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(440): CJoinElement->runQuery(Object(CJoinQuery))
#3 D:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1361): CActiveFinder->query(Object(CDbCriteria), false)
#5 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1461): CActiveRecord->query(Object(CDbCriteria))
#6 D:\xampp\htdocs\rrhh\protected\controllers\SitioController.php(27): CActiveRecord->find(Array)
#7 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SitioController->actionIndex()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#13 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#15 {main}
REQUEST_URI=/rrhh/
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 10:57:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 10:57:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 10:59:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 11:00:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 11:01:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 11:01:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 11:29:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 11:29:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 11:29:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 11:29:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 11:29:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "index" solicitada.' in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('index')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Hojadevida/inde...')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/rrhh/Hojadevida/index
HTTP_REFERER=http://localhost/rrhh/
---
2015/12/08 11:31:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "index" solicitada.' in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('index')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Hojadevida/inde...')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/rrhh/Hojadevida/index
---
2015/12/08 11:32:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "index" solicitada.' in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('index')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Hojadevida/inde...')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/rrhh/Hojadevida/index
---
2015/12/08 11:32:42 [error] [exception.CException] exception 'CException' with message 'HojadevidaController no ha podido encontrar la vista "crearHojaVida" solicitada.' in D:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('crearHojaVida', Array, true)
#1 D:\xampp\htdocs\rrhh\protected\controllers\HojadevidaController.php(12): CController->render('crearHojaVida', Array)
#2 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): HojadevidaController->actionIndex()
#3 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Hojadevida/inde...')
#8 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#10 {main}
REQUEST_URI=/rrhh/Hojadevida/index
---
2015/12/08 11:32:46 [error] [exception.CException] exception 'CException' with message 'HojadevidaController no ha podido encontrar la vista "crearHojaVida" solicitada.' in D:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('crearHojaVida', Array, true)
#1 D:\xampp\htdocs\rrhh\protected\controllers\HojadevidaController.php(12): CController->render('crearHojaVida', Array)
#2 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): HojadevidaController->actionIndex()
#3 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Hojadevida')
#8 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#10 {main}
REQUEST_URI=/rrhh/Hojadevida/
---
2015/12/08 11:33:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/Hojadevida/
---
2015/12/08 11:37:22 [error] [php] Missing argument 1 for CController::__construct(), called in D:\xampp\htdocs\rrhh\protected\controllers\HojadevidaController.php on line 11 and defined (D:\xampp\htdocs\yii\framework\web\CController.php:110)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\xampp\htdocs\yii\framework\web\CController.php(286): HojadevidaController->runAction()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(265): HojadevidaController->runActionWithFilters()
#3 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): HojadevidaController->run()
#4 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#6 D:\xampp\htdocs\rrhh\index.php(14): CWebApplication->run()
REQUEST_URI=/rrhh/Hojadevida/
in D:\xampp\htdocs\rrhh\protected\controllers\HojadevidaController.php (11)
in D:\xampp\htdocs\rrhh\index.php (14)
2015/12/08 11:37:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "libs/bootbox.min.js"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('libs/bootbox.mi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\xampp\htdocs\rrhh\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/rrhh/libs/bootbox.min.js
HTTP_REFERER=http://localhost/rrhh/Hojadevida/
---
